	waitUntil {serverTime==5400};
	minaret0 say3D "adhan";
	minaret1 say3D "adhan";
	minaret2 say3D "adhan";
	minaret3 say3D "adhan";
	minaret4 say3D "adhan";
	minaret5 say3D "adhan";
	minaret6 say3D "adhan";
	minaret7 say3D "adhan";
	minaret8 say3D "adhan";
	minaret9 say3D "adhan";
	minaret10 say3D "adhan";
	minaret11 say3D "adhan";